// Generated by pxr/usdImaging/hdEmscripten/bindgen/generate_bindings.py.
// Do not edit by hand; edit bindgen/core-bindings.json instead.

declare type IntVector = {
    size(): number,
    get(index: number): number,
    delete(): void,
}

declare type DoubleVector = {
    size(): number,
    get(index: number): number,
    delete(): void,
}

declare type StringVector = {
    size(): number,
    get(index: number): string,
    delete(): void,
}

declare type USDPrimVector = {
    size(): number,
    get(index: number): USDPrim,
    delete(): void,
}

declare type USDLayer = {
    GetIdentifier(): string,
    GetDisplayName(): string,
    ExportToString(): string,
    Export(path: string): boolean,
    Save(): boolean,
}

declare type USDAttribute = {
    IsValid(): boolean,
    GetName(): string,
    GetPath(): string,
    GetTypeName(): string,
    GetValueString(): string,
    GetValueStringAtTime(timeCode: number): string,
    SetBool(value: boolean, timeCode: number): boolean,
    SetInt(value: number, timeCode: number): boolean,
    SetFloat(value: number, timeCode: number): boolean,
    SetDouble(value: number, timeCode: number): boolean,
    SetString(value: string, timeCode: number): boolean,
    SetToken(value: string, timeCode: number): boolean,
    AddConnection(path: string): boolean,
    SetColor3f(r: number, g: number, b: number, timeCode: number): boolean,
    SetVec3f(x: number, y: number, z: number, timeCode: number): boolean,
    SetVec3d(x: number, y: number, z: number, timeCode: number): boolean,
    SetMatrix4d(m00: number, m01: number, m02: number, m03: number, m10: number, m11: number, m12: number, m13: number, m20: number, m21: number, m22: number, m23: number, m30: number, m31: number, m32: number, m33: number, timeCode: number): boolean,
}

declare type USDRelationship = {
    IsValid(): boolean,
    GetName(): string,
    GetPath(): string,
    GetTargets(): StringVector,
    AddTarget(path: string): boolean,
    ClearTargets(removeSpec: boolean): boolean,
}

declare type USDPrim = {
    IsValid(): boolean,
    GetName(): string,
    GetPath(): string,
    GetTypeName(): string,
    IsActive(): boolean,
    SetActive(active: boolean): boolean,
    ApplyAPI(schemaIdentifier: string): boolean,
    IsDefined(): boolean,
    IsLoaded(): boolean,
    GetParent(): USDPrim,
    GetChildren(): USDPrimVector,
    GetPropertyNames(): StringVector,
    GetAttribute(name: string): USDAttribute,
    CreateAttribute(name: string, typeName: string, custom: boolean): USDAttribute,
    GetRelationship(name: string): USDRelationship,
    CreateRelationship(name: string, custom: boolean): USDRelationship,
    AddVariant(variantSetName: string, variantName: string): boolean,
    SetVariantSelection(variantSetName: string, variantName: string): boolean,
    GetVariantSelection(variantSetName: string): string,
    ClearVariantSelection(variantSetName: string): boolean,
    BlockVariantSelection(variantSetName: string): boolean,
    GetVariantNames(variantSetName: string): StringVector,
    DefinePrimInVariant(variantSetName: string, variantName: string, path: string, typeName: string): USDPrim,
}

declare type USDStage = {
    GetRootLayer(): USDLayer,
    GetPseudoRoot(): USDPrim,
    GetPrimAtPath(path: string): USDPrim,
    DefinePrim(path: string, typeName: string): USDPrim,
    Traverse(): USDPrimVector,
    GetStartTimeCode(): number,
    GetEndTimeCode(): number,
    GetTimeCodesPerSecond(): number,
    SetStartTimeCode(timeCode: number): void,
    SetEndTimeCode(timeCode: number): void,
    SetTimeCodesPerSecond(timeCodesPerSecond: number): void,
    GetUpAxis(): number,
    SetUpAxis(upAxis: string): boolean,
    Export(path: string): boolean,
    ExportToString(): string,
}

declare function CreateStage(path: string): USDStage
declare function OpenStage(path: string): USDStage
declare function ReleaseStage(stage: USDStage): boolean
declare function CreateUsdzPackage(assetPath: string, usdzPath: string): boolean
declare function ReadFile(path: string): Uint8Array